---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tower-ingress
  namespace: "${TOWER_NAMESPACE}"
spec:
  rules:
    - host: "${TOWER_HOSTNAME}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
...
